name: medplusapp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  cached_network_image: ^3.3.0
  country_pickers: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  grouped_list: ^5.1.2
  hooks_riverpod: ^2.4.10
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/WorkSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/WorkSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/WorkSansItalicRegular.ttf
          weight: 400
        - asset: assets/fonts/WorkSansItalicMedium.ttf
          weight: 500
        - asset: assets/fonts/WorkSansRomanLight.ttf
          weight: 300
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
